# Numpy version

Numpy version >1.19 makes some ever so small changes to the test data making them not pass. It appears to be the vapor pressure from HRRR because the air temperature is fine but not variables derived from vapor pressure like precip temperature and thermal.

- air temperature is exactly the same from HRRR
- relative humidity is exactly the same from HRRR
- vapor pressure is float noise


In [1]:
import pandas as pd
import numpy as np

In [2]:
# air temperature
old = pd.read_csv('../ta_old.csv', parse_dates=True, index_col='date_time')
new = pd.read_csv('../ta_new.csv', parse_dates=True, index_col='date_time')
d = old - new
np.unique(d)

array([0.])

In [3]:
# relative humidity
old = pd.read_csv('../rh_old.csv', parse_dates=True, index_col='date_time')
new = pd.read_csv('../rh_new.csv', parse_dates=True, index_col='date_time')
d = old - new
np.unique(d)

array([0.])

In [4]:
# vapor pressure
old = pd.read_csv('../vp_old.csv', parse_dates=True, index_col='date_time')
new = pd.read_csv('../vp_new.csv', parse_dates=True, index_col='date_time')
d = old - new
np.unique(d)


array([-2.11303719e-04, -2.09472666e-04, -7.00683595e-05, -6.70166046e-05,
       -5.78613290e-05, -1.80358875e-05,  0.00000000e+00,  1.29699711e-04,
        1.82006839e-04,  1.91406260e-04])